version: '3.9'

configs:
  db_init:
    file: ./postgres/db_init.sql

services:
  postgres_kafka:
    container_name: postgres_kafka
    image: docker.io/timescale/timescaledb:latest-pg16
    environment:
      POSTGRES_DB: admin
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    healthcheck:
      test: pg_isready -U postgres
      interval: 5s
      start_period: 5s
    volumes:
      - postgres_kafka:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    command: [ "postgres", "-c", "log_statement=all" ]
    configs:
      - source: db_init
        target: /docker-entrypoint-initdb.d/db_init.sql
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka-server-1:
    container_name: kafka-server-1
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-server-1:9092,PLAINTEXT_HOST://kafka-server-1:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-server-2:
    container_name: kafka-server-2
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "39092:39092"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-server-2:9092,PLAINTEXT_HOST://kafka-server-2:39092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  manager:
    container_name: manager
    image: sheepkiller/kafka-manager
    ports:
      - "9000:9000"
    environment:
      ZK_HOSTS: zookeeper:2181
    depends_on:
      - zookeeper
  kafka-exam:
    container_name: kafka-exam
    pull_policy: always
    image: garikhgh/kafka-exam:latest
    depends_on:
      - postgres_kafka
      - kafka-server-1
      - kafka-server-2
      - manager
    ports:
      - "8081:8081"
volumes:
  postgres_kafka: